### ISSUE TITLE
Request To reference The "Easily Monitor Containerized Applications with Amazon CloudWatch Container Insights" Tutorial in the EKS Best Practices Guide

### ISSUE THREAD

**Issue by ahmadt312** [aws-observability/observability-best-practices#111]
Hi team!

I recently published a tutorial (keeping best practices in mind) on monitoring an [application's performance using CloudWatch Container Insights](https://community.aws/tutorials/navigating-amazon-eks/eks-monitor-containerized-applications). 

I would like to suggest that the [EKS Observability best practices guide](https://aws-observability.github.io/observability-best-practices/guides/containers/aws-native/eks/amazon-cloudwatch-container-insights/) should include a reference to the above tutorial, adding a lot of value as it explores more than just the setup process, providing detailed guidance on utilizing CloudWatch Log Insights for effective search and querying, as well as instructions for leveraging the CloudWatch dashboard for efficient monitoring.

I read through the best EKS practices guide, and found that the section (highlighted in the screenshot below) would be a great place to reference it.

PR created.

Thanks in advance,

Ahmad (Containers Specialist SA, AWS)

**Comment by ahmadt312** [comment]
![Screenshot 2023-12-20 at 10 05 37](https://github.com/aws-observability/observability-best-practices/assets/32881885/85b44d79-8018-496c-8ba8-59bbd01855c5)

**Comment by elamaran11** [comment]
@normalfaults @ahmadt312 IMO best practice guide is not heading to finer implementation details and since we already have a working page of this, we can hyper link this page in a sentence to say.... Please check this page on Easily Monitor Containerized Applications with Amazon CloudWatch Container Insights to deep dive on ....... something like this and hyper link. We dont want repeatative content.

**Comment by elamaran11** [comment]
@awsimaya Yes we are covering it in different pages like CI, Log Aggregation etc. This page linked is having all in one place but it has super finer implementation details. So i recommend just hyper link this page somewhere if people want to refer the implementation details.

**Comment by ahmadt312** [comment]
@elamaran11 The [PR](https://github.com/aws-observability/observability-best-practices/pull/112) is already created link this tutorial as a hyperlink.
