### ISSUE TITLE
Logs Insights Example Query

### ISSUE THREAD

**Issue by arrowroot** [aws-observability/observability-best-practices#16]
## CloudWatch Query Statement

```
stats count(errorCode) as eventCount by eventSource, eventName, awsRegion, userAgent, errorCode
| filter errorCode = 'ThrottlingException' 
| sort eventCount desc
```

## What is the purpose of this query?

The query provides a quick way to understand highest API Throttling errors grouped by error category in a particular time window. This can narrow down the API call and the AWS service in the region where the API requests are throttled.

## How do I use this query?

Use this query against the CloudTrail log groups (when CloudTrail is configured to log to CloudWatch Logs). Select the desired time frame for the query (ex. past 3 hours).

**Comment by lewinkedrs** [comment]
Closing issue, addressed in #18
