### ISSUE TITLE
Essential Metrics - Incorrect metric definition

### ISSUE THREAD

**Issue by meetreks** [aws-observability/observability-best-practices#38]
## API server request latency sum

ex:
Value in the table: The response latency distribution in microseconds for each verb, resource and subresource
Actual Definition: Cumulative Counter which tracks total time taken by the K8 API server to process requests.

**Comment by awsimaya** [comment]
Can you post the URL related to this issue here?

**Comment by meetreks** [comment]
https://aws-observability.github.io/observability-best-practices/guides/containers/oss/eks/best-practices-metrics-collection/
<html>
<body>


API server request latency sum | apiserver_request_latencies_sum | The response latency distribution in microseconds for each verb, resource and subresource
-- | -- | --



</body>
</html>
