### ISSUE TITLE
Incorrect Link

### ISSUE THREAD

**Issue by meetreks** [aws-observability/observability-best-practices#40]
There is a Incorrect link which is described here 

CoreDNS Metrics[¶](https://aws-observability.github.io/observability-best-practices/guides/containers/oss/eks/best-practices-metrics-collection/#coredns-metrics)
CoreDNS is a flexible, extensible DNS server that can serve as the Kubernetes cluster DNS. The CoreDNS pods provide name resolution for all pods in the cluster. Running DNS intensive workloads can sometimes experience intermittent CoreDNS failures due to DNS throttling, and this can impact applications.

Checkout the latest best practices for tracking key [CoreDNS performance metrics here.](**https://aws.github.io/aws-eks-best-practices/networking/CoreDNS/**)
<< Refer above for the broken link >>

**Comment by awsimaya** [comment]
@elamaran11 , can you take a look at this?

**Comment by elamaran11** [comment]
@normalfaults This again points to [Essential Metrics](https://aws-observability.github.io/observability-best-practices/guides/containers/oss/eks/best-practices-metrics-collection/#coredns-metrics) which points to CoreDNS in EKS Best Practices Guide which does not exist, were you envisioning to link any other link for CoreDNS ?
