### ISSUE TITLE
CURE Dashboard is not a JSON 

### ISSUE THREAD

**Issue by HFSVBC** [aws-observability/observability-best-practices#7]
Hi, I am trying to import the dashboard linked bellow but the file contains an HTML source code instead of JSON.
`sandbox/cure-grafana-dashboard/AmazonManagedGrafanaCUREDashboard.json`

Thank you

**Comment by lewinkedrs** [comment]
Hi @HFSVBC can you provide some more detail around this? Is this a dashboard that you found in the best-practices guide? Can you specify where this came from?

**Comment by babumiriyala** [comment]
Hi @lewinkedrs / @rmcdonough , I too trying to _Create Cost and Usage Report (CURE) Grafana Dashboard_ from the source `sandbox/cure-grafana-dashboard/AmazonManagedGrafanaCUREDashboard.json`. But actually the file name says `.Json `and the content inside has `HTML` code. Can you please update the same. Thank you. 

And the reference source link - [https://aws.amazon.com/blogs/mt/visualize-and-gain-insights-into-your-aws-cost-and-usage-with-amazon-managed-grafana/](url)

**Comment by lewinkedrs** [comment]
Closing as fixed with pr #13
